export interface Device {
    airDensity: number
    airFlow: number
    bathVentPos: number
    board_version: number
    bypassVentPos: number
    co2: number
    co2Indicator: number
    comfortLevel: number
    coolingPower: number
    deicing: boolean
    exhaustFilterIndicator: number
    exhaustTemp: number
    extractFanRPM: number
    extractHum: number
    extractHumAbs: number
    extractHumidityIndicator: number
    extractTemp: number
    extractVentPos: number
    extractFilterFul: boolean
    filter_hours: number
    hasErrors: boolean
    heatRecovery: number
    operating_hours: number
    operatingMode: number
    operatingModeName: string
    outdoorFilterIndicator: number
    outdoorHum: number
    outdoorHumAbs: number
    outdoorTemp: number
    powerRecovery: number
    pressure: number
    program: number
    programName: string
    roomArea: number
    rssi: number
    secondRoomFlow: number
    supplyFanRPM: number
    supplyFilterFul: boolean
    supplyTemp: number
    supplyVentPos: number
    timestamp: number
    version: string
}