blank_issues_enabled: false
contact_links:
    - name: ioBroker Community
      url: https://forum.iobroker.net/topic/82154/test-adapter-freeair
      about: Please ask and answer questions here
